name: Cleanup Workflow Runs

on:
  schedule:
    - cron: "0 0 */15 * *" # 每15天凌晨0点运行
  workflow_dispatch: # 也可以手动触发

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run cleanup script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node cleanup.js
