
name: wen json

on:
  # schedule:
    #- cron: '0 0 */10 * *'  # 每10天午夜执行
  workflow_dispatch:  # 手动触发器

jobs:
  update-spider:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        node-version: '20'

    - name: Install Dependencies
      run: python -m pip install requests

    - name: Get Spider Field and set environment variable
      run: |
        SPIDER_URL=$(python -c "import requests; print(requests.get('https://9280.kstore.space/wex.json').json()['spider'])")
        echo "SPIDER_URL=$SPIDER_URL" >> $GITHUB_ENV

    - name: Update Spider Field
      run: |
        response=$(curl -s 'https://4645.kstore.space/wex.json')
        updated_data=$(echo $response | python -c "import sys, json; data = json.load(sys.stdin); data['spider'] = '${{ env.SPIDER_URL }}'; print(json.dumps(data))")
        echo "$updated_data" > wex.json

    - name: Upload to KStore
      env:
        KSTORE_TOKEN: ${{ secrets.KSTORE_TOKEN }}
      run: |
        curl https://upload.kstore.space/upload/0?access_token=$KSTORE_TOKEN -F "file=@wex.json"
